spring:
  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog01?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*xml
common:
  #jwt密钥
  jwt-secret: blogSecret
  #jwt Token 名字
  jwt-tokenName: BLOG_TOKEN
  #jwt 前缀
  jwt-token-prefix: Jobeth_Blog_
  #jwt 过期时间
  jwt-expiration: 3000000
  #jwt 刷新时间
  jwt-refresh-time: 60000
  #jwt 不拦截的请求
  ant-matcher: /sys/login,/sys/logout,
  #系统权限配置缓存Redis key
  redis-url-perm-key: redis_url_perm
  #系统 根菜单标志
  root-menu-id: 0
  #blog 博客文章缓存Redis key 前缀
  redis-blog-prefix: redis_blog_
  #blog 博客缓存时间
  blog-cache-time: 3600000
server:
  port: 7070
  # 打印sql
logging:
  level:
    com.jobeth.perm.mapper: debug